# ============================================================
# vcf9-hcl-check.ps1  —  Standalone HCL Compatibility Checker
# ============================================================
# 사용 예시:
#   .\vcf9-hcl-check.ps1 -InventoryPath "C:\powercli\vSphere_Inventory_20260629_1627"
#
#   -InventoryPath : vcf9-precheck-script-cs.ps1 가 생성한 출력 폴더 경로 (필수)
#                    폴더 안에 Hosts_Hardware.csv, Physical_NICs.csv,
#                    HBA_Cards.csv, RAID_Controllers.csv 가 있어야 합니다.
#   -HCLPath       : VMware HCL CSV 4종이 들어있는 폴더 경로 (선택)
#                    미지정 시 스크립트와 같은 위치의 'hcl' 하위 폴더를 자동으로 사용합니다.
#                    'hcl' 폴더가 없으면 에러 메시지와 함께 종료합니다.
#   ⚠ 경로 끝에 백슬래시(\)는 붙이지 마세요. (예: "C:\hcl" (O) / "C:\hcl\" (X))
#
# 권장 폴더 구조:
#   C:\powercli\
#    ├─ vcf9-precheck-script-cs.ps1
#    ├─ vcf9-hcl-check.ps1
#    └─ hcl\
#        ├─ CPU_Series_9_0.csv
#        ├─ CPU_Series_9_1.csv
#        ├─ IO_Devices_9_0.csv
#        ├─ IO_Devices_9_1.csv
#        ├─ Systems_Servers_9_0.csv
#        ├─ Systems_Servers_9_1.csv
#        ├─ vSAN_IO_Controller_9_0.csv
#        └─ vSAN_IO_Controller_9_1.csv
param(
    [Parameter(Mandatory = $true)]
    [string]$InventoryPath,

    [Parameter(Mandatory = $false)]
    [string]$HCLPath
)

Set-StrictMode -Off
$ErrorActionPreference = "Continue"

Write-Host "===============================================================================" -ForegroundColor Cyan
Write-Host "  VCF9 Standalone Hardware Compatibility Checker" -ForegroundColor Cyan
Write-Host "===============================================================================" -ForegroundColor Cyan

# ── 입력 폴더 확인 ──
$InventoryPath = $InventoryPath.Trim().TrimEnd('\', '/')
if (-not (Test-Path $InventoryPath)) {
    Write-Host "[ERROR] Inventory folder not found: '$InventoryPath'" -ForegroundColor Red
    Exit
}

$HWFile     = Join-Path $InventoryPath "Hosts_Hardware.csv"
$NICFile    = Join-Path $InventoryPath "Physical_NICs.csv"
$HBAFile    = Join-Path $InventoryPath "HBA_Cards.csv"
$RAIDFile   = Join-Path $InventoryPath "RAID_Controllers.csv"

if (-not (Test-Path $HWFile)) {
    Write-Host "[ERROR] Hosts_Hardware.csv not found in '$InventoryPath'." -ForegroundColor Red
    Write-Host "        Please specify the folder generated by vcf9-precheck-script-cs.ps1." -ForegroundColor Red
    Exit
}

Write-Host "[INFO] Loading inventory data from: $InventoryPath" -ForegroundColor Gray
$HWReport   = Import-Csv -Path $HWFile   -Encoding UTF8
$PnicReport = if (Test-Path $NICFile)  { Import-Csv -Path $NICFile  -Encoding UTF8 } else { @() }
$HbaReport  = if (Test-Path $HBAFile)  { Import-Csv -Path $HBAFile  -Encoding UTF8 } else { @() }
$RaidReport = if (Test-Path $RAIDFile) { Import-Csv -Path $RAIDFile -Encoding UTF8 } else { @() }

Write-Host "       Hosts: $(@($HWReport).Count)  |  NICs: $(@($PnicReport).Count)  |  HBAs: $(@($HbaReport).Count)  |  RAID Controllers: $(@($RaidReport).Count)" -ForegroundColor DarkGray

# 결과 폴더: 스크립트 위치에 compatibility_YYYYMMDD_HHMM 폴더를 생성해서 저장
$ScriptBase  = if ($PSScriptRoot) { $PSScriptRoot } else { Split-Path -Parent $MyInvocation.MyCommand.Definition }
$TimeStamp   = Get-Date -Format "yyyyMMdd_HHmm"
$ReportDir   = Join-Path $ScriptBase "compatibility_$TimeStamp"
if (-not (Test-Path $ReportDir)) { New-Item -ItemType Directory -Path $ReportDir | Out-Null }
Write-Host "[INFO] Results will be saved to: $ReportDir" -ForegroundColor Gray

$vCenter   = "N/A (standalone run)"

# ── HCL 폴더 탐색 ──
# 기본값: 스크립트와 같은 위치의 'hcl' 하위 폴더 (대소문자 무관)
# -HCLPath 옵션으로 직접 지정한 경우에는 그 경로를 우선 사용합니다.
if (-not [string]::IsNullOrWhiteSpace($HCLPath)) {
    $HCLPath = $HCLPath.Trim().TrimEnd('\', '/')
}

if ([string]::IsNullOrWhiteSpace($HCLPath)) {
    $ScriptDir = if ($PSScriptRoot) { $PSScriptRoot } else { Split-Path -Parent $MyInvocation.MyCommand.Definition }
    # 'hcl' 폴더명 대소문자 변형 모두 허용 (hcl / HCL / Hcl)
    $HCLCandidate = Get-ChildItem -Path $ScriptDir -Directory -ErrorAction SilentlyContinue |
                    Where-Object { $_.Name -ieq 'hcl' } |
                    Select-Object -First 1
    if ($HCLCandidate) {
        $HCLPath = $HCLCandidate.FullName
        Write-Host "[INFO] HCL folder auto-detected: $HCLPath" -ForegroundColor Gray
    } else {
        Write-Host ""
        Write-Host "[ERROR] HCL data folder not found." -ForegroundColor Red
        Write-Host "        Expected location: $(Join-Path $ScriptDir 'hcl')" -ForegroundColor Red
        Write-Host "        Please create an 'hcl' subfolder next to this script and place the" -ForegroundColor Red
        Write-Host "        HCL CSV files inside it (CPU_Series, IO_Devices, Systems_Servers, vSAN_IO_Controller)," -ForegroundColor Red
        Write-Host "        or specify the path explicitly with -HCLPath `"C:\your\hcl\folder`"." -ForegroundColor Red
        Exit
    }
}

# ============================================================
# HCL 함수 정의 (메인 스크립트와 동일)
# ============================================================

function Format-ReleaseText {
    param([string]$Text)
    if ([string]::IsNullOrWhiteSpace($Text)) { return "N/A" }
    return ($Text -replace '[\r\n]+', ', ').Trim()
}

function Get-Tokens {
    param([string]$Text)
    if ([string]::IsNullOrWhiteSpace($Text)) { return @() }
    return @(($Text.ToLower() -split '[^a-z0-9]+') | Where-Object { $_.Length -ge 2 })
}

function Get-TokenWeight {
    param([string]$Token)
    if ($Token -match '[0-9]') { return 3 } else { return 1 }
}

function Get-SimilarityScore {
    param([string]$Detected, [string]$HCLValue)
    $hTokens = @(Get-Tokens $HCLValue)
    if ($hTokens.Count -eq 0) { return 0 }
    $dTokens = @(Get-Tokens $Detected)
    $TotalWeight = 0; $MatchWeight = 0
    foreach ($t in $hTokens) {
        $w = Get-TokenWeight -Token $t
        $TotalWeight += $w
        if ($dTokens -contains $t) { $MatchWeight += $w }
    }
    if ($TotalWeight -eq 0) { return 0 }
    return [Math]::Round(($MatchWeight / $TotalWeight) * 100, 0)
}

function Find-BestHCLMatch {
    param([array]$Table, [hashtable]$Index, [string]$Detected, [string[]]$Fields)
    if (-not $Table -or @($Table).Count -eq 0) { return $null }
    $DetTokens = @(Get-Tokens $Detected)
    $Candidates = $null
    if ($Index) {
        foreach ($t in ($DetTokens | Sort-Object { -([int]($_ -match '[0-9]')) })) {
            if ($Index.ContainsKey($t)) { $Candidates = $Index[$t]; break }
        }
        if (-not $Candidates) { $Candidates = $Table }
    } else { $Candidates = $Table }
    $Best = $null; $BestScore = -1
    foreach ($Row in $Candidates) {
        $HCLText = ($Fields | ForEach-Object { $Row.$_ }) -join ' '
        $Score = Get-SimilarityScore -Detected $Detected -HCLValue $HCLText
        if ($Score -gt $BestScore) { $BestScore = $Score; $Best = $Row }
    }
    if ($null -eq $Best) { return $null }
    return [PSCustomObject]@{ Row = $Best; Score = $BestScore }
}

function Build-HCLIndex {
    param([array]$Table, [string[]]$Fields)
    $Index = @{}
    if (-not $Table -or @($Table).Count -eq 0) { return $Index }
    foreach ($Row in $Table) {
        $HCLText = ($Fields | ForEach-Object { $Row.$_ }) -join ' '
        $Tokens = @(Get-Tokens $HCLText)
        foreach ($t in $Tokens) {
            if (-not $Index.ContainsKey($t)) { $Index[$t] = [System.Collections.Generic.List[object]]::new() }
            $Index[$t].Add($Row)
        }
    }
    return $Index
}

function Get-CpuFamilyCodes {
    param([string]$SeriesText)
    return @([regex]::Matches($SeriesText, '[0-9][0-9A-Za-z]{2,5}') | ForEach-Object { ($_.Value -replace '[^0-9]', '') } | Where-Object { $_.Length -ge 2 })
}

function Find-CpuFamilyMatch {
    param([string]$DetectedModel, [string]$Vendor, [array]$CpuTable)
    if (-not $CpuTable -or @($CpuTable).Count -eq 0 -or [string]::IsNullOrWhiteSpace($DetectedModel)) { return $null }
    $Skus = @([regex]::Matches($DetectedModel, '\b[0-9]{4}\b') | ForEach-Object { $_.Value })
    if ($Skus.Count -eq 0) { return $null }
    $IsIntel = $Vendor -match '(?i)intel'
    foreach ($Row in $CpuTable) {
        $Codes = Get-CpuFamilyCodes -SeriesText $Row.'CPU Series'
        foreach ($Sku in $Skus) {
            foreach ($Code in $Codes) {
                if ($Code.Length -lt 2) { continue }
                $IsMatch = $false
                if ($IsIntel) { $IsMatch = ($Sku.Substring(0, 2) -eq $Code.Substring(0, 2)) }
                else { $IsMatch = ($Sku.Substring(3, 1) -eq $Code.Substring($Code.Length - 1)) -and ($Sku.Substring(0, 1) -eq $Code.Substring(0, 1)) }
                if ($IsMatch) { return [PSCustomObject]@{ Row = $Row; Sku = $Sku; Code = $Code } }
            }
        }
    }
    return $null
}

function Get-VersionedMatch {
    param([array]$Table90, [array]$Table91, [hashtable]$Index90, [hashtable]$Index91,
          [string]$Detected, [string[]]$Fields, [int]$Threshold)
    $Match90 = Find-BestHCLMatch -Table $Table90 -Index $Index90 -Detected $Detected -Fields $Fields
    $Match91 = Find-BestHCLMatch -Table $Table91 -Index $Index91 -Detected $Detected -Fields $Fields
    $Status90 = if ($Match90 -and $Match90.Score -ge $Threshold) { "OK" } else { "MISMATCH" }
    $Status91 = if ($Match91 -and $Match91.Score -ge $Threshold) { "OK" } else { "MISMATCH" }
    $Best = $null
    if ($Match90 -and $Match91) { $Best = if ($Match90.Score -ge $Match91.Score) { $Match90 } else { $Match91 } }
    elseif ($Match90) { $Best = $Match90 } elseif ($Match91) { $Best = $Match91 }
    return [PSCustomObject]@{ Status90 = $Status90; Status91 = $Status91; Match90 = $Match90; Match91 = $Match91; Best = $Best }
}

function Get-VersionedCpuMatch {
    param([array]$CpuTable90, [array]$CpuTable91, [string]$DetectedModel, [string]$Vendor)
    $Match90 = Find-CpuFamilyMatch -DetectedModel $DetectedModel -Vendor $Vendor -CpuTable $CpuTable90
    $Match91 = Find-CpuFamilyMatch -DetectedModel $DetectedModel -Vendor $Vendor -CpuTable $CpuTable91
    $Status90 = if ($Match90) { "OK" } else { "MISMATCH" }
    $Status91 = if ($Match91) { "OK" } else { "MISMATCH" }
    $Best = if ($Match90) { $Match90 } elseif ($Match91) { $Match91 } else { $null }
    return [PSCustomObject]@{ Status90 = $Status90; Status91 = $Status91; Match90 = $Match90; Match91 = $Match91; Best = $Best }
}

function Get-HCLFileType {
    param([string]$FilePath)
    try { $HeaderLine = Get-Content -Path $FilePath -TotalCount 1 -Encoding UTF8 -ErrorAction Stop } catch { return $null }
    if ([string]::IsNullOrWhiteSpace($HeaderLine)) { return $null }
    if ($HeaderLine -match 'CPUID' -and $HeaderLine -match 'CPU Series')   { return "CPU" }
    if ($HeaderLine -match 'Partner Name')                                 { return "Server" }
    if ($HeaderLine -match 'Device Type')                                  { return "IODevice" }
    if ($HeaderLine -match 'Brand Name' -and $HeaderLine -match 'Feature') { return "vSAN" }
    return $null
}

function Get-HCLFileVersion {
    param([string]$FileName)
    $Has90 = $FileName -match '9[_\.]0'
    $Has91 = $FileName -match '9[_\.]1'
    if ($Has90 -and -not $Has91) { return "9.0" }
    if ($Has91 -and -not $Has90) { return "9.1" }
    return "Both"
}

function Import-HCLData {
    param([string]$Path)
    $Result = [PSCustomObject]@{
        CPU90 = @(); CPU91 = @(); IODevice90 = @(); IODevice91 = @()
        Server90 = @(); Server91 = @(); vSAN90 = @(); vSAN91 = @(); FoundFiles = @()
    }
    if (-not (Test-Path $Path)) { return $Result }
    $CsvFiles = Get-ChildItem -Path $Path -Filter "*.csv" -File -ErrorAction SilentlyContinue
    foreach ($File in $CsvFiles) {
        $Type = Get-HCLFileType -FilePath $File.FullName
        if (-not $Type) { continue }
        try { $Data = Import-Csv -Path $File.FullName -Encoding UTF8 -ErrorAction Stop } catch { continue }
        $Version = Get-HCLFileVersion -FileName $File.Name
        switch ($Type) {
            "CPU"      { if ($Version -ne "9.1") { $Result.CPU90      += $Data }; if ($Version -ne "9.0") { $Result.CPU91      += $Data } }
            "IODevice" { if ($Version -ne "9.1") { $Result.IODevice90 += $Data }; if ($Version -ne "9.0") { $Result.IODevice91 += $Data } }
            "Server"   { if ($Version -ne "9.1") { $Result.Server90   += $Data }; if ($Version -ne "9.0") { $Result.Server91   += $Data } }
            "vSAN"     { if ($Version -ne "9.1") { $Result.vSAN90     += $Data }; if ($Version -ne "9.0") { $Result.vSAN91     += $Data } }
        }
        $Result.FoundFiles += "$($File.Name) -> $Type / ESXi $Version"
    }
    return $Result
}

# ── HCL 데이터 로드 ──
Write-Host "[1/3] Loading HCL data from: $HCLPath" -ForegroundColor Cyan
$HCLData     = Import-HCLData -Path $HCLPath
$CpuHCL90    = $HCLData.CPU90;      $CpuHCL91    = $HCLData.CPU91
$IOHCL90     = $HCLData.IODevice90; $IOHCL91     = $HCLData.IODevice91
$SystemHCL90 = $HCLData.Server90;   $SystemHCL91 = $HCLData.Server91
$VsanHCL90   = $HCLData.vSAN90;     $VsanHCL91   = $HCLData.vSAN91

$HasAnyHCLData = @($CpuHCL90 + $CpuHCL91 + $IOHCL90 + $IOHCL91 + $SystemHCL90 + $SystemHCL91 + $VsanHCL90 + $VsanHCL91).Count -gt 0
if (-not $HasAnyHCLData) {
    Write-Host ""
    Write-Host "[INFO] Hardware compatibility check was skipped: no HCL data files were found at '$HCLPath'." -ForegroundColor Cyan
    Write-Host "       Place the HCL CSV files (CPU_Series, IO_Devices, Systems_Servers, vSAN_IO_Controller)" -ForegroundColor Cyan
    Write-Host "       in the HCL folder next to this script, or specify the path with -HCLPath." -ForegroundColor Cyan
    Exit
}

if ($HCLData.FoundFiles.Count -gt 0) {
    Write-Host "[INFO] Recognized HCL files:" -ForegroundColor Gray
    $HCLData.FoundFiles | ForEach-Object { Write-Host "       - $_" -ForegroundColor DarkGray }
}

Write-Host "[2/3] Building HCL index..." -ForegroundColor Cyan
$MatchThreshold = 50
$ServerFields  = @('Partner Name', 'Model'); $IOFields = @('Brand Name', 'Model')
$Idx_Server90  = Build-HCLIndex -Table $SystemHCL90 -Fields $ServerFields
$Idx_Server91  = Build-HCLIndex -Table $SystemHCL91 -Fields $ServerFields
$Idx_Net90     = Build-HCLIndex -Table @($IOHCL90 | Where-Object { $_.'Device Type' -match 'Network' })    -Fields $IOFields
$Idx_Net91     = Build-HCLIndex -Table @($IOHCL91 | Where-Object { $_.'Device Type' -match 'Network' })    -Fields $IOFields
$Idx_Storage90 = Build-HCLIndex -Table @($IOHCL90 | Where-Object { $_.'Device Type' -notmatch 'Network' }) -Fields $IOFields
$Idx_Storage91 = Build-HCLIndex -Table @($IOHCL91 | Where-Object { $_.'Device Type' -notmatch 'Network' }) -Fields $IOFields
$Idx_Vsan90    = Build-HCLIndex -Table $VsanHCL90  -Fields $IOFields
$Idx_Vsan91    = Build-HCLIndex -Table $VsanHCL91  -Fields $IOFields
Write-Host "       Index build complete." -ForegroundColor DarkGray

# ── 호환성 검사 ──
Write-Host "[3/3] Running compatibility checks..." -ForegroundColor Cyan

$IOHCL_Network_90 = @($IOHCL90 | Where-Object { $_.'Device Type' -match 'Network' })
$IOHCL_Network_91 = @($IOHCL91 | Where-Object { $_.'Device Type' -match 'Network' })
$IOHCL_Storage_90 = @($IOHCL90 | Where-Object { $_.'Device Type' -notmatch 'Network' })
$IOHCL_Storage_91 = @($IOHCL91 | Where-Object { $_.'Device Type' -notmatch 'Network' })

$ComplianceReport = @()

# --- Server & CPU ---
foreach ($HW in $HWReport) {
    $DetectedServerText = "$($HW.Vendor) $($HW.Model)"
    $ServerMatch = Get-VersionedMatch -Table90 $SystemHCL90 -Table91 $SystemHCL91 -Index90 $Idx_Server90 -Index91 $Idx_Server91 -Detected $DetectedServerText -Fields $ServerFields -Threshold $MatchThreshold

    $ServerScore   = if ($ServerMatch.Best) { $ServerMatch.Best.Score } else { 0 }
    $ServerHCLText = if ($ServerMatch.Best) { "$($ServerMatch.Best.Row.'Partner Name') $($ServerMatch.Best.Row.Model)" } else { "N/A" }
    $ServerNote    = if ($ServerMatch.Best) { "VCF Supported: $($ServerMatch.Best.Row.'VCF Supported. Confirm w/Vendor')  /  Releases: $(Format-ReleaseText $ServerMatch.Best.Row.'Supported Releases')" } else { "No matching entry in HCL Systems/Servers" }
    if ($ServerMatch.Status90 -eq "MISMATCH" -or $ServerMatch.Status91 -eq "MISMATCH") { $ServerNote = "[Best candidate, manual verification required] " + $ServerNote }

    $Sockets           = if ($HW.CPU_Sockets -and [int]$HW.CPU_Sockets -gt 0) { [int]$HW.CPU_Sockets } else { 0 }
    $CoresPerSocket    = if ($HW.CPU_CoresPerSocket -and [int]$HW.CPU_CoresPerSocket -gt 0) { [int]$HW.CPU_CoresPerSocket } else { 0 }
    $EffCoresPerSocket = if ($CoresPerSocket -lt 16) { 16 } else { $CoresPerSocket }
    $EffTotalCores     = $Sockets * $EffCoresPerSocket
    $CoreNote          = if ($CoresPerSocket -lt 16 -and $Sockets -gt 0) { "(actual ${CoresPerSocket} cores/socket -> raised to minimum 16)" } else { "" }

    $ComplianceReport += [PSCustomObject]@{
        "Cluster"               = if ($HW.Cluster) { $HW.Cluster } else { "N/A" }
        "HostName"              = $HW.HostName
        "Category"              = "Server"
        "Detected"              = $DetectedServerText
        "CPU_Sockets"           = $Sockets
        "CoresPerSocket_Actual" = $CoresPerSocket
        "CoresPerSocket_Eff"    = $EffCoresPerSocket
        "Total_Cores_Eff"       = $EffTotalCores
        "Core_Note"             = $CoreNote
        "HCL_Match"             = $ServerHCLText
        "Match_Score(%)"        = $ServerScore
        "ESXi_9.0"              = $ServerMatch.Status90
        "ESXi_9.1"              = $ServerMatch.Status91
        "Note"                  = $ServerNote
    }

    $DetectedCpuText = "$($HW.CPU_Vendor) / $($HW.CPU_Model)"
    $CpuMatch = Get-VersionedCpuMatch -CpuTable90 $CpuHCL90 -CpuTable91 $CpuHCL91 -DetectedModel $HW.CPU_Model -Vendor $HW.CPU_Vendor
    $CpuScore    = if ($CpuMatch.Best) { 100 } else { 0 }
    $CpuHCLText  = if ($CpuMatch.Best) { $CpuMatch.Best.Row.'CPU Series' } else { "N/A" }
    $CpuNote     = if ($CpuMatch.Best) { "SKU '$($CpuMatch.Best.Sku)' <-> Series code '$($CpuMatch.Best.Code)' generation match / Releases: $(Format-ReleaseText $CpuMatch.Best.Row.'Supported Releases')" } elseif (@($CpuHCL90 + $CpuHCL91).Count -gt 0) { "No matching generation (Series) found in CPU_Series list" } else { "No CPU HCL data available" }

    $ComplianceReport += [PSCustomObject]@{
        "Cluster"        = if ($HW.Cluster) { $HW.Cluster } else { "N/A" }
        "HostName"       = $HW.HostName
        "Category"       = "CPU"
        "Detected"       = $DetectedCpuText
        "HCL_Match"      = $CpuHCLText
        "Match_Score(%)" = $CpuScore
        "ESXi_9.0"       = $CpuMatch.Status90
        "ESXi_9.1"       = $CpuMatch.Status91
        "Note"           = $CpuNote
    }
}

# --- NIC ---
foreach ($Nic in $PnicReport) {
    $DetectedNicText = "$($Nic.Device) / $($Nic.Model)"
    $NicMatch = Get-VersionedMatch -Table90 $IOHCL_Network_90 -Table91 $IOHCL_Network_91 -Index90 $Idx_Net90 -Index91 $Idx_Net91 -Detected $Nic.Model -Fields $IOFields -Threshold $MatchThreshold
    $NicScore    = if ($NicMatch.Best) { $NicMatch.Best.Score } else { 0 }
    $NicHCLText  = if ($NicMatch.Best) { "$($NicMatch.Best.Row.'Brand Name') $($NicMatch.Best.Row.Model)" } else { "N/A" }
    $NicNote     = if ($NicMatch.Best) { "Releases: $(Format-ReleaseText $NicMatch.Best.Row.'Supported Releases')" } else { "No matching entry in IO Devices (Network)" }
    if ($NicMatch.Status90 -eq "MISMATCH" -or $NicMatch.Status91 -eq "MISMATCH") { $NicNote = "[Best candidate, manual verification required] " + $NicNote }

    $ComplianceReport += [PSCustomObject]@{
        "Cluster"        = if ($Nic.Cluster) { $Nic.Cluster } else { "N/A" }
        "HostName"       = $Nic.HostName
        "Category"       = "NIC"
        "Detected"       = $DetectedNicText
        "HCL_Match"      = $NicHCLText
        "Match_Score(%)" = $NicScore
        "ESXi_9.0"       = $NicMatch.Status90
        "ESXi_9.1"       = $NicMatch.Status91
        "Note"           = $NicNote
    }
}

# --- Storage Controller (HBA + RAID) ---
foreach ($Ctrl in (@($HbaReport) + @($RaidReport))) {
    $DetectedCtrlText = "$($Ctrl.Device) / $($Ctrl.Model)"
    $CtrlMatch = Get-VersionedMatch -Table90 $IOHCL_Storage_90 -Table91 $IOHCL_Storage_91 -Index90 $Idx_Storage90 -Index91 $Idx_Storage91 -Detected $Ctrl.Model -Fields $IOFields -Threshold $MatchThreshold
    $VsanMatch = Get-VersionedMatch -Table90 $VsanHCL90 -Table91 $VsanHCL91 -Index90 $Idx_Vsan90 -Index91 $Idx_Vsan91 -Detected $Ctrl.Model -Fields $IOFields -Threshold $MatchThreshold

    $CtrlScore   = if ($CtrlMatch.Best) { $CtrlMatch.Best.Score } else { 0 }
    $CtrlHCLText = if ($CtrlMatch.Best) { "$($CtrlMatch.Best.Row.'Brand Name') $($CtrlMatch.Best.Row.Model)" } else { "N/A" }
    $CtrlNote    = if ($CtrlMatch.Best) { "ESXi Releases: $(Format-ReleaseText $CtrlMatch.Best.Row.'Supported Releases')" } else { "No matching entry in IO Devices" }
    if ($CtrlMatch.Status90 -eq "MISMATCH" -or $CtrlMatch.Status91 -eq "MISMATCH") { $CtrlNote = "[Best candidate, manual verification required] " + $CtrlNote }
    if ($VsanMatch.Best) { $CtrlNote += "  |  vSAN candidate: $($VsanMatch.Best.Row.'Brand Name') $($VsanMatch.Best.Row.Model) (score $($VsanMatch.Best.Score)%, 9.0:$($VsanMatch.Status90)/9.1:$($VsanMatch.Status91))" }
    else { $CtrlNote += "  |  No vSAN I/O Controller match (not relevant if vSAN is not in use)" }

    $ComplianceReport += [PSCustomObject]@{
        "Cluster"        = if ($Ctrl.Cluster) { $Ctrl.Cluster } else { "N/A" }
        "HostName"       = $Ctrl.HostName
        "Category"       = "Storage_Controller"
        "Detected"       = $DetectedCtrlText
        "HCL_Match"      = $CtrlHCLText
        "Match_Score(%)" = $CtrlScore
        "ESXi_9.0"       = $CtrlMatch.Status90
        "ESXi_9.1"       = $CtrlMatch.Status91
        "Note"           = $CtrlNote
    }
}

# ── CSV 출력 ──
if ($ComplianceReport) {
    $ComplianceReport | Group-Object Category | ForEach-Object {
        $SafeName = $_.Name -replace '[^a-zA-Z0-9]', ''
        $_.Group | Export-Csv -Path "$ReportDir\Compatibility_$SafeName.csv" -NoTypeInformation -Encoding UTF8
    }
}

# ── HTML 리포트 ──
# HTML 헬퍼 함수
function ConvertTo-SafeHtml { param([string]$Text); if ($null -eq $Text) { return "" }; return [System.Net.WebUtility]::HtmlEncode($Text) }
function Get-Badge { param([string]$Status); if ($Status -eq "OK") { return '<span class="badge ok">OK</span>' } else { return '<span class="badge miss">MISMATCH</span>' } }
function Get-RowClass { param([string]$s90,[string]$s91); if ($s90 -eq "OK" -and $s91 -eq "OK") { "tr-ok" } elseif ($s90 -eq "MISMATCH" -and $s91 -eq "MISMATCH") { "tr-miss" } else { "tr-partial" } }
function Get-SafeFileName { param([string]$Text); if ([string]::IsNullOrWhiteSpace($Text)) { return "unknown" }; return ($Text -replace '[^a-zA-Z0-9_\-]', '_') }
function New-VersionCardPair {
    param([int]$FullCount,[int]$FullCores,[int]$MisCount,[int]$MisCores,[string]$Version)
    return @"
<div class="ver-group">
  <div class="ver-label">ESXi $Version</div>
  <div class="card-row">
    <div class="kpi-card green"><div class="kpi-icon">&#10003;</div><div class="kpi-body"><div class="kpi-val">$FullCount</div><div class="kpi-sub">100% Match Hosts</div><div class="kpi-detail">$FullCores physical cores total</div></div></div>
    <div class="kpi-card red"><div class="kpi-icon">&#10007;</div><div class="kpi-body"><div class="kpi-val">$MisCount</div><div class="kpi-sub">Mismatch Hosts</div><div class="kpi-detail">$MisCores physical cores total</div></div></div>
  </div>
</div>
"@
}

function New-CategoryTableHtml {
    param([array]$Rows, [string]$Category = "")
    $sb = New-Object System.Text.StringBuilder
    [void]$sb.AppendLine('<div class="table-wrap"><table>')
    if ($Category -eq "Server") {
        [void]$sb.AppendLine('<thead><tr><th>Host</th><th>Detected</th><th>Sockets</th><th>Cores/Socket(Actual)</th><th>Cores/Socket(Eff)</th><th>Total Cores(Eff)</th><th>Core Note</th><th>HCL Best Match</th><th>Score</th><th>ESXi 9.0</th><th>ESXi 9.1</th><th>Note</th></tr></thead><tbody>')
        foreach ($R in $Rows) {
            $rc = Get-RowClass -s90 $R.'ESXi_9.0' -s91 $R.'ESXi_9.1'
            $cn = if (-not [string]::IsNullOrWhiteSpace($R.Core_Note)) { "<span style=`"color:#b45309;font-weight:600`">$(ConvertTo-SafeHtml $R.Core_Note)</span>" } else { "" }
            [void]$sb.AppendLine("<tr class=`"$rc`"><td>$(ConvertTo-SafeHtml $R.HostName)</td><td>$(ConvertTo-SafeHtml $R.Detected)</td><td>$($R.CPU_Sockets)</td><td>$($R.CoresPerSocket_Actual)</td><td>$($R.CoresPerSocket_Eff)</td><td><strong>$($R.Total_Cores_Eff)</strong></td><td class=`"note`">$cn</td><td>$(ConvertTo-SafeHtml $R.HCL_Match)</td><td>$($R.'Match_Score(%)')%</td><td>$(Get-Badge $R.'ESXi_9.0')</td><td>$(Get-Badge $R.'ESXi_9.1')</td><td class=`"note`">$(ConvertTo-SafeHtml $R.Note)</td></tr>")
        }
    } else {
        [void]$sb.AppendLine('<thead><tr><th>Host</th><th>Detected</th><th>HCL Best Match</th><th>Score</th><th>ESXi 9.0</th><th>ESXi 9.1</th><th>Note</th></tr></thead><tbody>')
        foreach ($R in $Rows) {
            $rc = Get-RowClass -s90 $R.'ESXi_9.0' -s91 $R.'ESXi_9.1'
            [void]$sb.AppendLine("<tr class=`"$rc`"><td>$(ConvertTo-SafeHtml $R.HostName)</td><td>$(ConvertTo-SafeHtml $R.Detected)</td><td>$(ConvertTo-SafeHtml $R.HCL_Match)</td><td>$($R.'Match_Score(%)')%</td><td>$(Get-Badge $R.'ESXi_9.0')</td><td>$(Get-Badge $R.'ESXi_9.1')</td><td class=`"note`">$(ConvertTo-SafeHtml $R.Note)</td></tr>")
        }
    }
    [void]$sb.AppendLine('</tbody></table></div>')
    return $sb.ToString()
}

$SharedCss = @"
:root{--bg:#f0f2f5;--surface:#fff;--border:#e2e8f0;--primary:#1e3a5f;--primary-lt:#e8edf5;--green:#16a34a;--green-lt:#dcfce7;--green-dk:#14532d;--red:#dc2626;--red-lt:#fee2e2;--red-dk:#7f1d1d;--yellow:#d97706;--yellow-lt:#fef3c7;--gray:#64748b;--gray-lt:#f8fafc;--radius:12px;--shadow:0 1px 3px rgba(0,0,0,.08),0 4px 16px rgba(0,0,0,.06);font-family:'Malgun Gothic','Apple SD Gothic Neo',Arial,sans-serif}
*{box-sizing:border-box;margin:0;padding:0}body{background:var(--bg);color:#1e293b;padding:28px 32px;font-size:14px;line-height:1.6}
.page-header{margin-bottom:32px;display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:10px}.page-header h1{font-size:22px;font-weight:700;color:var(--primary);margin-bottom:4px}.page-meta{color:var(--gray);font-size:12px}
.back-link{font-size:13px;font-weight:600;color:var(--primary);text-decoration:none;background:var(--primary-lt);padding:7px 14px;border-radius:8px;white-space:nowrap}.back-link:hover{background:var(--primary);color:#fff}
.section-title{font-size:15px;font-weight:700;color:var(--primary);margin:28px 0 14px;display:flex;align-items:center;gap:8px}.section-title::before{content:'';display:inline-block;width:4px;height:18px;background:var(--primary);border-radius:2px}
.version-block{display:flex;gap:24px;margin-bottom:12px;width:100%}.ver-group{display:flex;flex-direction:column;gap:8px;flex:1;min-width:0}.ver-label{font-size:12px;font-weight:700;color:var(--primary);letter-spacing:.05em;text-transform:uppercase;padding:4px 0}.card-row{display:flex;gap:12px;width:100%}
.kpi-card{display:flex;align-items:center;gap:16px;background:var(--surface);border-radius:var(--radius);padding:20px 24px;box-shadow:var(--shadow);flex:1;min-width:0;border-left:5px solid}.kpi-card.green{border-color:var(--green)}.kpi-card.red{border-color:var(--red)}.kpi-icon{font-size:22px;font-weight:900}.kpi-card.green .kpi-icon{color:var(--green)}.kpi-card.red .kpi-icon{color:var(--red)}.kpi-val{font-size:30px;font-weight:700;line-height:1}.kpi-sub{font-size:12px;font-weight:600;color:var(--gray);margin-top:4px}.kpi-detail{font-size:17px;font-weight:700;color:#1e293b;margin-top:4px}
.cluster-section{background:var(--surface);border-radius:var(--radius);box-shadow:var(--shadow);padding:22px 24px;margin-bottom:24px}.cluster-header{display:flex;align-items:center;justify-content:space-between;margin-bottom:16px;flex-wrap:wrap;gap:8px}.cluster-name{font-size:15px;font-weight:700;color:var(--primary)}.cluster-name a{color:var(--primary);text-decoration:none;border-bottom:1.5px dashed var(--primary)}.cluster-name a:hover{color:#0f2440;border-bottom-style:solid}.cluster-cards{display:flex;gap:16px;width:100%;margin-bottom:18px}.cluster-ver-group{display:flex;flex-direction:column;gap:6px;flex:1;min-width:0}.cluster-ver-label{font-size:11px;font-weight:700;color:var(--gray);letter-spacing:.05em}.cluster-card-row{display:flex;gap:8px;width:100%}.c-card{display:flex;align-items:center;gap:10px;border-radius:10px;padding:12px 16px;flex:1;min-width:0;border:1.5px solid}.c-card.green{background:var(--green-lt);border-color:var(--green)}.c-card.red{background:var(--red-lt);border-color:var(--red)}.c-icon{font-size:17px;font-weight:900}.c-card.green .c-icon{color:var(--green)}.c-card.red .c-icon{color:var(--red)}.c-val{font-size:22px;font-weight:700;line-height:1}.c-sub{font-size:11px;color:var(--gray);margin-top:2px}.c-detail{font-size:15px;font-weight:700;color:#1e293b;margin-top:2px}
.summary-table-wrap{overflow-x:auto;margin-bottom:16px}.summary-table-wrap table{width:100%;border-collapse:collapse;font-size:13px}.summary-table-wrap th{background:var(--primary);color:#fff;padding:8px 12px;font-weight:600;text-align:left}.summary-table-wrap td{padding:7px 12px;border-bottom:1px solid var(--border)}.summary-table-wrap tr:last-child td{font-weight:700;background:var(--gray-lt)}.summary-table-wrap tr:hover td{background:var(--primary-lt)}
.cat-section{margin-bottom:20px}.cat-title{font-size:13px;font-weight:700;color:var(--primary);margin-bottom:8px;padding:6px 12px;background:var(--primary-lt);border-radius:6px;display:inline-block}
.table-wrap{overflow-x:auto}.table-wrap table{width:100%;border-collapse:collapse;font-size:12px}.table-wrap th{background:var(--primary);color:#fff;padding:7px 10px;font-weight:600;white-space:nowrap;text-align:left}.table-wrap td{padding:6px 10px;border-bottom:1px solid var(--border);vertical-align:top}.table-wrap .note{max-width:340px;font-size:11px;color:var(--gray)}
.tr-ok:hover td{background:#f0fdf4}.tr-miss td{background:#fff5f5}.tr-miss:hover td{background:#fee2e2}.tr-partial td{background:#fffbeb}.tr-partial:hover td{background:#fef3c7}
.badge{display:inline-flex;align-items:center;padding:2px 9px;border-radius:20px;font-size:11px;font-weight:700;letter-spacing:.02em}.badge.ok{background:var(--green-lt);color:var(--green-dk)}.badge.miss{background:var(--red-lt);color:var(--red-dk)}
.tag-total{display:inline-block;padding:2px 8px;border-radius:4px;background:var(--primary-lt);color:var(--primary);font-size:11px;font-weight:600}
"@

# 집계
$HWLookup = @{}; foreach ($hw in $HWReport) { $HWLookup[$hw.HostName] = $hw }
$HostSummary = $ComplianceReport | Group-Object HostName | ForEach-Object {
    $Rows = $_.Group; $hw = $HWLookup[$_.Name]
    $Cores = if ($hw -and $hw.Total_Cores) { [int]$hw.Total_Cores } else { 0 }
    [PSCustomObject]@{ HostName = $_.Name; Cluster = ($Rows | Select-Object -First 1).Cluster; Cores = $Cores
        AllOk90 = (@($Rows | Where-Object { $_.'ESXi_9.0' -ne "OK" }).Count -eq 0)
        AllOk91 = (@($Rows | Where-Object { $_.'ESXi_9.1' -ne "OK" }).Count -eq 0) }
}
$Full90Hosts = @($HostSummary | Where-Object { $_.AllOk90 }); $Mis90Hosts = @($HostSummary | Where-Object { -not $_.AllOk90 })
$Full91Hosts = @($HostSummary | Where-Object { $_.AllOk91 }); $Mis91Hosts = @($HostSummary | Where-Object { -not $_.AllOk91 })
$Full90Cores = ($Full90Hosts | Measure-Object -Property Cores -Sum).Sum; if ($null -eq $Full90Cores) { $Full90Cores = 0 }
$Mis90Cores  = ($Mis90Hosts  | Measure-Object -Property Cores -Sum).Sum; if ($null -eq $Mis90Cores)  { $Mis90Cores  = 0 }
$Full91Cores = ($Full91Hosts | Measure-Object -Property Cores -Sum).Sum; if ($null -eq $Full91Cores) { $Full91Cores = 0 }
$Mis91Cores  = ($Mis91Hosts  | Measure-Object -Property Cores -Sum).Sum; if ($null -eq $Mis91Cores)  { $Mis91Cores  = 0 }

$ClusterHostSummary = $HostSummary | Group-Object Cluster | ForEach-Object {
    $cH = $_.Group
    $cf90 = @($cH | Where-Object { $_.AllOk90 }); $cm90 = @($cH | Where-Object { -not $_.AllOk90 })
    $cf91 = @($cH | Where-Object { $_.AllOk91 }); $cm91 = @($cH | Where-Object { -not $_.AllOk91 })
    $cf90c = ($cf90 | Measure-Object -Property Cores -Sum).Sum; if ($null -eq $cf90c) { $cf90c = 0 }
    $cm90c = ($cm90 | Measure-Object -Property Cores -Sum).Sum; if ($null -eq $cm90c) { $cm90c = 0 }
    $cf91c = ($cf91 | Measure-Object -Property Cores -Sum).Sum; if ($null -eq $cf91c) { $cf91c = 0 }
    $cm91c = ($cm91 | Measure-Object -Property Cores -Sum).Sum; if ($null -eq $cm91c) { $cm91c = 0 }
    [PSCustomObject]@{ Cluster = $_.Name; TotalHosts = $cH.Count
        Full90Count = $cf90.Count; Full90Cores = $cf90c; Mis90Count = $cm90.Count; Mis90Cores = $cm90c; Mis90HostNames = ($cm90 | ForEach-Object { $_.HostName }) -join ', '
        Full91Count = $cf91.Count; Full91Cores = $cf91c; Mis91Count = $cm91.Count; Mis91Cores = $cm91c; Mis91HostNames = ($cm91 | ForEach-Object { $_.HostName }) -join ', ' }
} | Sort-Object Cluster

$CategorySummary = $ComplianceReport | Group-Object Category | ForEach-Object {
    $Ok90 = @($_.Group | Where-Object { $_.'ESXi_9.0' -eq "OK" }).Count
    $Ok91 = @($_.Group | Where-Object { $_.'ESXi_9.1' -eq "OK" }).Count
    [PSCustomObject]@{ Category = $_.Name; Total = $_.Count; Ok90 = $Ok90; Mis90 = $_.Count - $Ok90; Rate90 = if ($_.Count -gt 0) { [Math]::Round(($Ok90/$_.Count)*100,0) } else { 0 }; Ok91 = $Ok91; Mis91 = $_.Count - $Ok91; Rate91 = if ($_.Count -gt 0) { [Math]::Round(($Ok91/$_.Count)*100,0) } else { 0 } }
}
$TotalAll = $ComplianceReport.Count
$TotalOk90 = @($ComplianceReport | Where-Object { $_.'ESXi_9.0' -eq "OK" }).Count; $TotalMis90 = $TotalAll - $TotalOk90
$TotalOk91 = @($ComplianceReport | Where-Object { $_.'ESXi_9.1' -eq "OK" }).Count; $TotalMis91 = $TotalAll - $TotalOk91
$TotalRate90 = if ($TotalAll -gt 0) { [Math]::Round(($TotalOk90/$TotalAll)*100,0) } else { 0 }
$TotalRate91 = if ($TotalAll -gt 0) { [Math]::Round(($TotalOk91/$TotalAll)*100,0) } else { 0 }

# 메인 HTML 리포트
$Html = New-Object System.Text.StringBuilder
[void]$Html.AppendLine(@"
<!DOCTYPE html><html lang="ko"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>VCF9 HCL Compatibility Check</title><style>$SharedCss</style></head><body>
<div class="page-header"><div><h1>VCF9 Hardware Compatibility Check</h1><div class="page-meta">Generated: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss") &nbsp;|&nbsp; Source: $(ConvertTo-SafeHtml $InventoryPath) &nbsp;|&nbsp; Threshold: ${MatchThreshold}% = OK &nbsp;|&nbsp; ESXi 9.0 / 9.1 judged independently</div></div></div>
<div class="section-title">Overall Host Compatibility</div>
<div class="version-block">$(New-VersionCardPair -FullCount $Full90Hosts.Count -FullCores $Full90Cores -MisCount $Mis90Hosts.Count -MisCores $Mis90Cores -Version "9.0")$(New-VersionCardPair -FullCount $Full91Hosts.Count -FullCores $Full91Cores -MisCount $Mis91Hosts.Count -MisCores $Mis91Cores -Version "9.1")</div>
<div class="section-title">Per-Cluster Host Compatibility</div>
"@)

foreach ($CHS in $ClusterHostSummary) {
    $ClusterFileName = "Compatibility_Cluster_$(Get-SafeFileName $CHS.Cluster).html"
    [void]$Html.AppendLine('<div class="cluster-section">')
    [void]$Html.AppendLine("<div class=`"cluster-header`"><span class=`"cluster-name`">📦 Cluster: <a href=`"$ClusterFileName`">$(ConvertTo-SafeHtml $CHS.Cluster)</a></span><span class=`"tag-total`">$($CHS.TotalHosts) hosts</span></div>")
    [void]$Html.AppendLine('<div class="cluster-cards">')
    foreach ($ver in @(@{V="9.0";fc=$CHS.Full90Count;fco=$CHS.Full90Cores;mc=$CHS.Mis90Count;mco=$CHS.Mis90Cores;mh=$CHS.Mis90HostNames},@{V="9.1";fc=$CHS.Full91Count;fco=$CHS.Full91Cores;mc=$CHS.Mis91Count;mco=$CHS.Mis91Cores;mh=$CHS.Mis91HostNames})) {
        $misLabel    = if ([string]::IsNullOrWhiteSpace($ver.mh)) { "None" } else { $ver.mh }
        $misHostHtml = if ($ver.mc -gt 0) {
            '<div style="font-size:11px;color:#7f1d1d;margin-top:4px">Mismatch hosts: ' + (ConvertTo-SafeHtml $misLabel) + '</div>'
        } else { "" }
        [void]$Html.AppendLine(
            "<div class=`"cluster-ver-group`">" +
            "<div class=`"cluster-ver-label`">ESXi $($ver.V)</div>" +
            "<div class=`"cluster-card-row`">" +
            "<div class=`"c-card green`"><div class=`"c-icon`">&#10003;</div><div><div class=`"c-val`">$($ver.fc)</div><div class=`"c-sub`">100% Match</div><div class=`"c-detail`">$($ver.fco) cores</div></div></div>" +
            "<div class=`"c-card red`"><div class=`"c-icon`">&#10007;</div><div><div class=`"c-val`">$($ver.mc)</div><div class=`"c-sub`">Mismatch</div><div class=`"c-detail`">$($ver.mco) cores</div></div></div>" +
            "</div>$misHostHtml</div>"
        )
    }
    [void]$Html.AppendLine('</div></div>')
}

[void]$Html.AppendLine('<div class="section-title">Part Summary</div><div class="summary-table-wrap"><table>')
[void]$Html.AppendLine('<thead><tr><th>Part</th><th>Total</th><th>9.0 OK</th><th>9.0 MISS</th><th>9.0 Rate</th><th>9.1 OK</th><th>9.1 MISS</th><th>9.1 Rate</th></tr></thead><tbody>')
foreach ($S in $CategorySummary) { [void]$Html.AppendLine("<tr><td>$(ConvertTo-SafeHtml $S.Category)</td><td>$($S.Total)</td><td>$($S.Ok90)</td><td>$($S.Mis90)</td><td>$($S.Rate90)%</td><td>$($S.Ok91)</td><td>$($S.Mis91)</td><td>$($S.Rate91)%</td></tr>") }
[void]$Html.AppendLine("<tr><td>Total</td><td>$TotalAll</td><td>$TotalOk90</td><td>$TotalMis90</td><td>$TotalRate90%</td><td>$TotalOk91</td><td>$TotalMis91</td><td>$TotalRate91%</td></tr></tbody></table></div>")
[void]$Html.AppendLine('</body></html>')

$Html.ToString() | Out-File -FilePath "$ReportDir\Compatibility_Report.html" -Encoding UTF8

# 클러스터별 상세 HTML
$CategoryOrder = @("Server","CPU","NIC","Storage_Controller")
$ClusterGroups = $ComplianceReport | Group-Object Cluster | Sort-Object Name
$ClusterFileList = @()

foreach ($CG in $ClusterGroups) {
    $ClusterFileName = "Compatibility_Cluster_$(Get-SafeFileName $CG.Name).html"
    $ClusterFileList += $ClusterFileName
    $CluHtml = New-Object System.Text.StringBuilder
    [void]$CluHtml.AppendLine("<!DOCTYPE html><html lang=`"ko`"><head><meta charset=`"UTF-8`"><meta name=`"viewport`" content=`"width=device-width,initial-scale=1`"><title>VCF9 HCL - $(ConvertTo-SafeHtml $CG.Name)</title><style>$SharedCss</style></head><body>")
    [void]$CluHtml.AppendLine("<div class=`"page-header`"><div><h1>Cluster: $(ConvertTo-SafeHtml $CG.Name) - Compatibility Detail</h1><div class=`"page-meta`">Generated: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss") &nbsp;|&nbsp; Source: $(ConvertTo-SafeHtml $InventoryPath)</div></div><a class=`"back-link`" href=`"Compatibility_Report.html`">&#8592; Back to Summary</a></div>")
    $ExistingCats = @($CG.Group.Category | Select-Object -Unique)
    $OrderedCats  = @($CategoryOrder | Where-Object { $ExistingCats -contains $_ })
    $OtherCats    = @($ExistingCats | Where-Object { $CategoryOrder -notcontains $_ })
    foreach ($Cat in (@($OrderedCats)+@($OtherCats))) {
        $CatRows = @($CG.Group | Where-Object { $_.Category -eq $Cat } | Sort-Object HostName)
        [void]$CluHtml.AppendLine("<div class=`"cat-section`"><div class=`"cat-title`">$(ConvertTo-SafeHtml $Cat) <span class=`"tag-total`">$($CatRows.Count) items</span></div>")
        [void]$CluHtml.AppendLine((New-CategoryTableHtml -Rows $CatRows -Category $Cat))
        [void]$CluHtml.AppendLine('</div>')
    }
    [void]$CluHtml.AppendLine('</body></html>')
    $CluHtml.ToString() | Out-File -FilePath "$ReportDir\$ClusterFileName" -Encoding UTF8
}

# 콘솔 요약
$Mismatches = $ComplianceReport | Where-Object { $_.'ESXi_9.0' -eq "MISMATCH" -or $_.'ESXi_9.1' -eq "MISMATCH" }
Write-Host ""
Write-Host "===============================================================================" -ForegroundColor Yellow
Write-Host " VCF9 Hardware Compatibility Check Summary (ESXi 9.0 / 9.1)" -ForegroundColor Yellow
Write-Host "===============================================================================" -ForegroundColor Yellow
Write-Host " Total checked: $($ComplianceReport.Count)  |  ESXi 9.0 MISMATCH: $TotalMis90  |  ESXi 9.1 MISMATCH: $TotalMis91  |  Threshold: $MatchThreshold%" -ForegroundColor Gray
if ($Mismatches) {
    $Mismatches | Sort-Object HostName, Category | ForEach-Object {
        Write-Host (" [MISMATCH] {0,-25} {1,-20} {2,-45} (9.0:{3} / 9.1:{4})" -f $_.HostName, $_.Category, $_.Detected, $_.'ESXi_9.0', $_.'ESXi_9.1') -ForegroundColor Red
        Write-Host ("            -> Best HCL candidate: {0} ({1}%)" -f $_.HCL_Match, $_.'Match_Score(%)') -ForegroundColor DarkGray
    }
} else {
    Write-Host " All items match the HCL for both ESXi 9.0 and 9.1." -ForegroundColor Green
}
Write-Host "===============================================================================" -ForegroundColor Yellow
Write-Host " NOTE: CPU matching is based on model series (generation), not exact SKU." -ForegroundColor DarkGray
Write-Host " NOTE: All other parts use weighted token similarity scoring (best-effort)." -ForegroundColor DarkGray
Write-Host " CSV files: Compatibility_Server / CPU / NIC / StorageController.csv" -ForegroundColor Gray
Write-Host " HTML summary: Compatibility_Report.html" -ForegroundColor Gray
Write-Host " Cluster detail HTML ($($ClusterFileList.Count) files): $($ClusterFileList -join ', ')" -ForegroundColor Gray
Write-Host " Source inventory: $InventoryPath" -ForegroundColor Gray
Write-Host " Output folder:    $ReportDir" -ForegroundColor Gray
Write-Host "===============================================================================" -ForegroundColor Yellow
